version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql-laravel
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 3377
      MYSQL_DATABASE: drivenow
      MYSQL_USER: laravel
      MYSQL_PASSWORD: 3377
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
